from enum import Enum

class ResponseEnum(Enum):

    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_VALIDATE_SUCCESSFULLY = "FILE_VALIDATE_SUCCESSFULLY"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    PROCESSING_SUCCESS = "PROCESSING_SUCCESS"
    NO_FILE_EXIST = "NO_FILE_EXIST"